### PR TITLE
This branch adds nested objects (useful for when you have a lot of data attributes) and auto-adds helpers and dynamicHelpers when using the express adapter

### PR DESCRIPTION
**Pull request by colinta**

### CODE REVIEW

**Comment by mauricemach** [comment]
Why nuke examples and docs? :)

**Comment by colinta** [comment]
oops!  shoot.  I was using it for a local project - don't merge THAT.

**Comment by colinta** [comment]
gonna resend this once I get the examples and docs back in.. probably by rebasing 29ab966

**Comment by colinta** [comment]
this pull request has been replaced: https://github.com/mauricemach/coffeekup/pull/78

**Pull request closed without merging**
