### PR TITLE
npm failed to require 'coffeekup'

### PR DESCRIPTION
**Pull request by davidarkemp**
fix for issue #28

### CODE REVIEW

**Comment by niclashoyer** [comment]
this fixed the issue for me with the following node and npm versions:

<pre><code>$ node -v && npm -v
v0.5.0-pre
0.3.18
</code></pre>

**Comment by niclashoyer** [comment]
I have to revoke. The actual fix would be

<pre><code>diff --git a/index.js b/index.js
index 1859138..c9ca547 100644
--- a/index.js
+++ b/index.js
@@ -1 +1 @@
-module.exports = require('./coffeekup')
+module.exports = require('./lib/coffeekup')
</code></pre>

**Comment by niclashoyer** [comment]
See commit here from orlin, this should be merged with master:
https://github.com/orlin/coffeekup/commit/9aee2a73e5e1bffee54a600a45b51fea9d5ac1a1

**Comment by mauricemach** [comment]
Fix didn't work for me, please see issue [#28](https://github.com/mauricemach/coffeekup/issues/28)

**Pull request closed without merging**
