### PR TITLE
fixed two bugs: packaging (npm >= 1) and @body in context (express@2.2.1)

### PR DESCRIPTION
**Pull request by aldonline**

### CODE REVIEW

**Comment by tanepiper** [comment]
@mauricemach +1 - running this fork until the main version is fixed

**Comment by naneau** [comment]
Looks good to me :)

**Comment by randallb** [comment]
+1. Can't use CoffeeKup till this gets merged.

**Comment by mauricemach** [comment]
Fixed express issues on the new [0.2.4beta](https://github.com/mauricemach/coffeekup/tree/0.2.4beta) branch. Please check the annotated source on [/docs](https://github.com/mauricemach/coffeekup/tree/0.2.4beta/docs) and the (still rough) changelog notes on the readme, tell me what you think and if it works for you!

**Comment by randallb** [comment]
Awesome. Wasn't immediately clear how the context vars changed, but now that I've figured it out, I'm a fan.

Going to be using this now going forward. Thx!

**Comment by randallb** [comment]
Strange issue... not sure if it's directly related. (Express 2.4.2, btw)

works:
`text @body
    text "alright"`

works:

`````` @body````

doesn't work:
````@body
    text "alright"````
``````

**Comment by mauricemach** [comment]
`@body` alone works because it means `return this.body`. The snippet that doesn't work compiles down to `this.body; text('alright')`. Since the body in this case is neither passed to the text function nor returned, there's no way it could end up in the template buffer.

**Comment by randallb** [comment]
Ahh got it. Oh random returns, how you mess with my mind.

PS- I vote for a Coffeekup IRC room... let's get this community going! :)

**Pull request closed without merging**
