### PR TITLE
Okay, here's a fresh new clone that has nested objects and express helpers

### PR DESCRIPTION
**Pull request by colinta**
Helpers are, in other express view engines, locals.  So I expected app.helpers() and app.dynamicHelpers() to be available in coffeekup.  Instead, coffeekup used only its own `locals` and `hardcoded` mechanism.  This automatically loads helpers into `hardcoded`, and dynamicViewHelpers into `locals`

``` coffeescript
app.helpers
  sheet: (sheet)->
    link
      href: sheet
      rel: 'stylesheet'
      type: 'text/css'
```

``` coffeescript
head ->
  sheet '/css/styles.css'
```

The other feature this brings in is the ability to group `data` attributes (or others, I suppose, but I can't think of any).

``` coffeescript
a href:'/login', data: {icon:'arrow-r', iconpos:'right'}, 'Login'
```

``` html
<a href="/login" data-icon="arrow-r" data-iconpos="right">Login</a>
```

### CODE REVIEW

**Comment by mauricemach** [comment]
Merged prefixed attributes, nice use of objects as attribute values, thanks!

As for express helpers, I think you're a little confused here:

> Helpers are, in other express view engines, locals. So I expected app.helpers() and app.dynamicHelpers() to be available in coffeekup.

They are. Everything that's available as a local in other engines - data, helpers, options, etc - is a context variable in CoffeeKup. Which by the way is also the case with [Eco](github.com/sstephenson/eco). I don't know about Eco, but in CoffeeKup this is because "tags" are locals, and we don't want them colliding with data, helpers and options all the time. So by default things are put in the context, and optionally you can also make them locals or hardcoded, if you know what you're doing and you think it's a good fit semantically:

``` coffeescript
app.helpers
  file: __filename

  locals:
    basename: require('path').basename

  hardcode:
    sheet: (sheet)->
      link
        href: sheet
        rel: 'stylesheet'
        type: 'text/css'
```

``` coffeescript
doctype 5
html ->
  head ->
    title 'Foo'
    sheet basename(@file, '.coffee') + '.css'
```

Probably a stupid example, but you get the meaning.

**Comment by colinta** [comment]
I'm with you on data, 100%.  It's only helpers that I disagree - I think of them as more like a "plugin" – for instance my `sheet` helper is just a short hand for `link href: x, type: 'text/css'`, and so I place it on the same playing field as div/p/etc.  I don't think they are request specific, which is the case for data.  And so `@` symbolizes the parts of my template that are transient, and locals are the parts that are built-in & global.

Put another way - if there was a plugin feature on coffeekup, those would surely be available as locals (am I right in that assumption)?  What is a helper, if not a "plugin" that extends the template engine's default functionality?  To me, to two things are the same thing.

**Comment by mauricemach** [comment]
I'm not sure if you got my point. I do agree 100% that `sheet` is a good fit for hardcoding. I just don't think we should make all helpers _necessarily_ hardcoded, eliminating the other two options (making a helper a "dynamic" local or a context variable). Do you?

**Comment by colinta** [comment]
I _do_ think so, but in researching evidence in favor of my argument, I found uses of express helpers that I totally disagree with.

Most notably, from express' documentation:

http://expressjs.com/guide.html#app.helpers()

``` javascript
app.helpers({
    name: function(first, last){ return first + ', ' + last }
  , firstName: 'tj'
  , lastName: 'holowaychuk'
});
```

In this example, he assigns some arbitrary variables (firstName and lastName).  This is, I think, _not_ a good use-case for helpers.  I think of helpers the way rails defines them, and the way they are defined here: https://github.com/masahiroh/express-helpers (for instance)

So perhaps what I should be aiming at is not modifying the core, but considering a plugin system that would _faciliate_ this type of behavior - e.g. allow me to add a plugin that in turn assigns express helpers as hardcodes.  That way, I would know that _my_ apps were behaving how I wanted, but I wouldn't bother the community-at-large.

**Comment by mauricemach** [comment]
Well, thanks to `app.register`, you can already do that. Just write your own adapter that wraps `coffeekup.adapters.express` and use it instead:

``` coffeescript
app.register '.coffee', require 'myadapter'
```

**Comment by colinta** [comment]
Man is this thread old!  I'm closing it up just for cleanliness.

Ah, how I miss my days of node and coffeescript.  I was lobbying for my company to switch to node (from PHP), but there was a big python movement that sprung up, and I couldn't really argue with that.  Anyway, hope all is well!

**Pull request closed without merging**
