### PR TITLE
options.compile to inhibit rendering

### PR DESCRIPTION
**Pull request by dvv**
Please, consider pulling
--Vladimir

### CODE REVIEW

**Comment by mauricemach** [comment]
Hi Vladimir,

If you need to compile a template to js without rendering it, specially considering it's just plain CoffeeScript, wouldn't `CoffeeScript.compile template` be more straightforward and make more sense than `CoffeeKup.render template, options: {compile: true}`?. That's the beauty of reusing the language, you can also reuse its tools. You could even make use of any of the dozens of CoffeeScript compilation schemes available like rack-coffee, BistroCar, Barista, coffee-haml-filter etc at coffeescript.org/#resources (half the projects there seem to be about that!). Does it make sense to you in your scenario? What do you think?

**Comment by dvv** [comment]
Right you are, of course plain .compile() will suffice. Thanks for the clue! I nullify the patch except, may be, reducing some `options?.` to be just `options.` since at the very top of .render() we already are sure `options` are set.

--Vladimir

**Comment by mauricemach** [comment]
That's very right, that was from a sloppy refactoring, thanks for spotting. Now I'm just trying to figure out the best way to pick up only those changes from your commit. [edit] Do you have a suggestion?

**Comment by dvv** [comment]
I guess you can just pull and then delete the line returning code if option.compile. Then recompile *.coffee and push again. OTOH, I'd leave the options.compile stuff since then the single entry point (.render()) sustained. So far we just coffee.compile(), but later some preparations may appear... Am i clear?

Another feature I'd like to implement is to compile a template to a named function to be pushed into tags[]. That way we could achieve partials dirt cheap.

--Vladimir

**Comment by mauricemach** [comment]
Done, merged in the fixes sans option.compile. Not sure I'm following you on the single entry point thing though, can you clarify?

I'll have a look later on the partials issue. You can already add new "tags" by passing in functions as options.locals to .render, but to really make partials viable I think some things still have to be ironed out.

**Comment by mauricemach** [comment]
Now that user-defined locals are working fine, have a look at this [gist](http://gist.github.com/650620). This is a simple user-defined way to take a template in function form and use it as a partial. I'll probably add this by default later, even though I'm wary of polluting the locals namespace, I think in this case it's really worth it.

But now I understand what you mean by compiling the template to a standalone function that is independent of the rendering engine. That's an interesting feature indeed, and I'll look further into it.

**Pull request merged**
